os:
  - linux

dist: xenial
services:
  - xvfb
language: node_js
node_js:
  - lts/*
  - node

before_install:
  - curl --location http://rawgit.com/twolfson/fix-travis-ci/master/lib/install.sh | bash -s

script:
  - npm install
  - npm audit --production
  - gulp
